config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :posts, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :deals, only: [:show, :new, :create, :edit, :update, :destroy]

  resources :users, only: [:show, :edit, :update, :destroy]

  resources :chat_boards

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: "users/passwords",
    sessions: "users/sessions"
  }

end

app/models/board_user_relation.rb
class BoardUserRelation < ActiveRecord::Base
  belongs_to :user
  belongs_to :chat_board
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :posts
end

app/models/chat.rb
class Chat < ActiveRecord::Base

  belongs_to :chat_board
  belongs_to :users
end

app/models/chat_board.rb
class ChatBoard < ActiveRecord::Base
  has_many :board_user_relations
  has_many :users, through: :board_user_relations
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :post
  belongs_to :requester, class_name: 'User', foreign_key: :requester_id
  belongs_to :contractor, class_name: 'User', foreign_key: :contractor_id

  enum status: %w[applied accepted working delivered paid rejected]
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :place
  has_many :deal
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :board_user_relations
  has_many :chat_boards, through: :board_user_relations
  has_many :chats

  def icon
    'user_icon.png'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_boards_controller.rb
class ChatBoardsController < ApplicationController
  def index
    @chat_boards = ChatBoard.all
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  def show
    @deal = Deal.find(params[:id])
    @requester = @deal.requester
    @contractor = @deal.contractor
    @post = @deal.post
    @chat_board = @requester.boards.joins(:board_user_relation).having("board_user_relations.user_id = ?", @contractor.id)&.first.presence || ChatBoard.new
    if @deal.requester_id == current_user.id
      @deal_treat = 'request'
    elsif @deal.contractor_id == current_user.id
      @deal_treat = 'contract'
    else
      redirect_to root_path
    end
  end

  def create
    binding.pry
    deal = Deal.create(deal_params)
    redirect_to deal_path(deal)
  end

  private

  def deal_params
    params.require(:deal).permit(:post_id, :requester_id, :contractor_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post.create(post_params)
  end

  private
  def post_params
    params.require(:post).permit(:title, :contetn, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
     super
  end

  # POST /resource/sign_in
  def create
     super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deals/show.html.erb
<div id="main" class="deals-show">
  <h2>依頼内容</h2>
  <%= image_tag @requester.icon %>
  <div class="post-created">
    <%= time_ago_in_words @post.created_at%> ago
  </div>
  <div class="post-title">
    <%= @post.title %>
  </div>
  <div class="post-content">
    <%= @post.content %>
  </div>
  <div class="deal-constractor">
    <p>
      請負人: <%= @contractor.name %>
    </p>
  </div>
  <% if @deal_treat == "request" %>
    <div class="deal-status">
      <% case @deal.status %>
      <% when "applied" %>
        <p>ステータス: 応募中</p>
      <% when "accepted" %>
        <p>ステータス: 応募承認済み</p>
      <% when "working" %>
        <p>ステータス: 実行中</p>
      <% when "delivered" %>
        <p>ステータス: 配送中</p>
      <% when "paid" %>
        <p>ステータス: 完了</p>
      <% when  "rejected" %>
        この請負人には依頼しませんでした。
      <% end %>
    </div>
  <% elsif @deal_treat == "contract" %>
    <div class="deal-status">
      <% case @deal.status %>
      <% when "applied" %>
        <p>ステータス: 応募中</p>
        <p>応募の承認を待ちましょう</p>
      <% when "accepted" %>
        <p>ステータス: 応募承認済み</p>
        <p>応募が承認されました。下のボタンを押して依頼を実行しましょう。</p>
      <% when "working" %>
        <p>ステータス: 実行中</p>
        <p></p>
        <%= link_to chat_board_path(@chat_board) %>
      <% when "delivered" %>
        <p>ステータス: 配送完了</p>
      <% when "paid" %>
        <p>ステータス: 依頼完了</p>
      <% when  "rejected" %>
        この依頼は別の人が請け負いました。
        別の依頼を探しましょう。
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav id="header">
  <%= image_tag "logo.png"%>
  <div class="header-sign">
    <% if current_user.present? %>
      <%= link_to "マイページ", user_path(current_user) %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tanomigoto</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/posts/_posts.html.erb
<div class="posts-list">
  <ul>
    <% posts.each do |post| %>
      <li>
        <%= link_to post_path(post), class: "post_link" do %>
          <div class="post-user">
            <%= image_tag post.user.icon %>
            <br>
            <%= post.user.name %>
          </div>
          <div class="post-created">
            <%= time_ago_in_words post.created_at%> ago
          </div>
          <div class="post-title">
            <%= post.title %>
          </div>
          <div class="post-content">
            <%= post.content %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/show.html.erb
<div id="main" class="posts-show">
  <div class="post-user">
    <%= image_tag @post.user.icon %>
    <br>
    <%= @post.user.name %>
  </div>
  <div class="post-created">
    <%= time_ago_in_words @post.created_at%> ago
  </div>
  <div class="post-title">
    <%= @post.title %>
  </div>
  <div class="post-content">
    <%= @post.content %>
  </div>
  <% if current_user.present? && @post.user != current_user %>
    <%= link_to "頼みごとを受ける", deals_path(params: { deal: { post_id: @post.id, requester_id: @post.user.id, contractor_id: current_user.id }}), method: :post %>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div id="main" class="posts-index">
  <div class="">
    <% if @posts.present? %>
      <%= render 'posts/posts', posts: @posts %>
    <% end %>
  </div>
</div>